version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - chatApp

  chat-app:
    image: chat-app
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/chat_application
    networks:
      - chatApp
    depends_on:
      - mongodb

networks:
  chatApp:
    driver: bridge