name: Build and Push Image to ACR
on:
  push:
    branches: [ "WIChatApp" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        uses: azure/docker-login@v1
        with:
          login-server: chatwebappcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push
        run: |
          docker build -t chatwebappcontainerregistry.azurecr.io/chat-app:${{ github.sha }}
          docker push chatwebappcontainerregistry.azurecr.io/chat-app:${{ github.sha }}
